CalisanBilgiler/CalisanBilgiler/Models/CalisanViewModel.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalisanBilgiler.Models
{
    public class CalisanViewModel
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Date Of Birth")]
        public DateTime DateOfBirth { get; set; }
        [DisplayName("E-mail")]
        public string Email { get; set; }
		[DisplayName("Salary")]
		public double Salary { get; set; }
        [DisplayName("Name")]
        public String FullName 
        {
            get { return FirstName + " " + LastName; }
     }
    }
}

CalisanBilgiler/CalisanBilgiler/Models/DBEntities/Calisan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalisanBilgiler.Models.DBEntities
{
    public class Calisan
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Column(TypeName ="varchar(50)")]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public double Salary { get; set; }





    }
}

CalisanBilgiler/CalisanBilgiler/Models/ErrorViewModel.cs
namespace CalisanBilgiler.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CalisanBilgiler/CalisanBilgiler/Controllers/CalisanController.cs
using CalisanBilgiler.DataErisimKatmani_DAL_;
using CalisanBilgiler.Models;
using CalisanBilgiler.Models.DBEntities;
using Microsoft.AspNetCore.Mvc;

namespace CalisanBilgiler.Controllers
{
    public class CalisanController : Controller
    {
        private readonly CalisanDbContext _context;

        public CalisanController(CalisanDbContext context)
        {
            this._context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var calisans=_context.Calisans.ToList();
			List<CalisanViewModel> calisanList = new List<CalisanViewModel>();
			if (calisans != null)
            {   
                
                foreach (var calisan in calisans)
                {
                    var CalisanViewModel=new CalisanViewModel()
                    {
                        Id=calisan.Id,
                        FirstName=calisan.FirstName,
                        LastName=calisan.LastName,
                        DateOfBirth=calisan.DateOfBirth,
                        Email=calisan.Email,
                        Salary=calisan.Salary,

                    };
					calisanList.Add(CalisanViewModel);
				}
				return View(calisanList);
			}
            return View(calisanList);
        }

        [HttpGet]
        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CalisanViewModel calisanData) {
            try
            {
                if (ModelState.IsValid)
                {
                    var calisan = new Calisan()
                    {
                        FirstName = calisanData.FirstName,
                        LastName = calisanData.LastName,
                        DateOfBirth = calisanData.DateOfBirth,
                        Email = calisanData.Email,
                        Salary = calisanData.Salary,
                    };
                    _context.Calisans.Add(calisan);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Calisan Basariyla Kaydedildi";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Data Dogru Degil";
                    return View();
                }
            }
            catch (Exception ex)
            {

				TempData["errorMessage"] = ex.Message;
				return View();
			}
            
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            try
            {
                var calisan = _context.Calisans.SingleOrDefault(x => x.Id == Id);
                if (calisan != null)
                {
                    var calisanView = new CalisanViewModel()
                    {
                        Id = calisan.Id,
                        FirstName = calisan.FirstName,
                        LastName = calisan.LastName,
                        DateOfBirth = calisan.DateOfBirth,
                        Email = calisan.Email,
                        Salary = calisan.Salary,

                    };
                    return View(calisanView);
                }
                else
                {
                    TempData["errorMessage"] = $"Bu Id'li bir calisan yok: {Id}";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
				TempData["errorMessage"] = ex.Message;
				return RedirectToAction("Index");
            }
          
        }
        [HttpPost]
        public IActionResult Edit(CalisanViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var calisan = new Calisan()
                    {
                        Id = model.Id,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        DateOfBirth = model.DateOfBirth,
                        Email = model.Email,
                        Salary = model.Salary,

                    };
                    _context.Calisans.Update(calisan);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Calisan Bilgileri Basariyla Guncellendi";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Bilgiler hatali";
                    return View();
                }
            }
            catch (Exception ex)
            {
				TempData["errorMessage"] = ex.Message;
				return View();

			}
         
        }

		[HttpGet]
		public IActionResult Delete(int Id)
		{
			try
			{
				var calisan = _context.Calisans.SingleOrDefault(x => x.Id == Id);
				if (calisan != null)
				{
					var calisanView = new CalisanViewModel()
					{
						Id = calisan.Id,
						FirstName = calisan.FirstName,
						LastName = calisan.LastName,
						DateOfBirth = calisan.DateOfBirth,
						Email = calisan.Email,
						Salary = calisan.Salary,

					};
					return View(calisanView);
				}
				else
				{
					TempData["errorMessage"] = $"Bu Id'li bir calisan yok: {Id}";
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return RedirectToAction("Index");
			}

		}
        [HttpPost]
        public IActionResult Delete(CalisanViewModel model)
        {
            try
            {
                var calisan = _context.Calisans.SingleOrDefault(x => x.Id == model.Id);
                if (calisan != null)
                {
                    _context.Calisans.Remove(calisan);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Calisan Basariyla Silindi";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = $"Bu Id'li bir calisan yok: {model.Id}";
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
				TempData["errorMessage"] = ex.Message;
				return View();
			}
           
        }
	}
}

CalisanBilgiler/CalisanBilgiler/Controllers/HomeController.cs
using CalisanBilgiler.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CalisanBilgiler.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CalisanBilgiler/CalisanBilgiler/Views/Calisan/Create.cshtml
@model CalisanBilgiler.Models.CalisanViewModel

@{
	ViewData["Title"] = "Create Employee";
	var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>@ViewData["Title"]</h3>
</hr>
@if (!string.IsNullOrWhiteSpace(@errorMessage))
{
<div class="alert alert-danger">
	<strong>Error!</strong>@errorMessage
		<button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>

</div>
}
<form action="Create" method="post" autocomplete="off">
	<div class="mb-3">
		<label class="form-label">First Name</label>
		<input type="text" class="form-control" asp-for="FirstName"/>
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">Last Name</label>
		<input type="text" class="form-control" asp-for="LastName" />
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">Date Of Birth</label>
		<input type="date" class="form-control" asp-for="DateOfBirth" />
		<span asp-validation-for="DateOfBirth" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">E-Mail</label>
		<input type="email" class="form-control" asp-for="Email" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">Salary</label>
		<div class="input-group">
			<span class="input-group-text">₺</span>
			<input type="text" class="form-control" asp-for="Salary" />
			<span asp-validation-for="Salary" class="text-danger"></span>
		</div>
		
	</div>
	<div class="d-grid">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>
@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");

	}
}

CalisanBilgiler/CalisanBilgiler/Views/Calisan/Delete.cshtml
@model CalisanBilgiler.Models.CalisanViewModel
@{
	ViewData["Title"] = "Delete Employee";
	var errorMessage = TempData["errorMessage"]?.ToString();

}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(@errorMessage))
{
	<div class="alert alert-danger">
		<strong>Error!</strong>@errorMessage
		<button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>

	</div>
}
<form action="Delete" method="post" autocomplete="off">
	<div class="mb-3">
		<label class="form-label">Id</label>
		<input type="text" class="form-control" asp-for="Id" readonly></input>
	</div>
	<div class="mb-3">
		<label class="form-label">First Name</label>
		<input type="text" class="form-control" asp-for="FirstName" readonly></input>
	</div>
	<div class="mb-3">
		<label class="form-label">Last Name</label>
		<input type="text" class="form-control" asp-for="LastName" readonly></input>
	</div>
	<div class="mb-3">
		<label class="form-label"> Date Of Birth</label>
		<input type="date" class="form-control" asp-for="DateOfBirth" readonly></input>
	</div>
	<div class="mb-3">
		<label class="form-label">E-Mail</label>
		<input type="email" class="form-control" asp-for="Email" readonly></input>
		
	</div>
	<div class="mb-3">
		<label class="form-label">Salary</label>
		<div class="input-group">
			<span class="input-group-text">₺</span>
			<input type="text" class="form-control" asp-for="Salary" readonly></input>

		</div>
		
	</div>
	<div class="d-grid">
		<button type="submit" class="btn btn-danger" onclick="return confirm('Bu calisani silmek istediginize emin misiniz:
		@Model.FullName')">Delete</button>
	</div>
</form>

CalisanBilgiler/CalisanBilgiler/Views/Calisan/Edit.cshtml
@model CalisanBilgiler.Models.CalisanViewModel
@{
	ViewData["Title"] = "Edit Employee";
	var errorMessage=TempData["errorMessage"]?.ToString();
	
}
<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(@errorMessage))
{
	<div class="alert alert-danger">
		<strong>Error!</strong>@errorMessage
		<button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>

	</div>
}
<form action="Edit" method="post" autocomplete="off">
	<div class="mb-3">
		<label class="form-label">Id</label>
		<input type="text" class="form-control" asp-for="Id" readonly></input>
	</div>
	<div class="mb-3">
		<label class="form-label">First Name</label>
		<input type="text" class="form-control" asp-for="FirstName"></input>
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">Last Name</label>
		<input type="text" class="form-control" asp-for="LastName"></input>
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label"> Date Of Birth</label>
		<input type="date" class="form-control" asp-for="DateOfBirth"></input>
		<span asp-validation-for="DateOfBirth" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">E-Mail</label>
		<input type="email" class="form-control" asp-for="Email"></input>
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label class="form-label">Salary</label>
		<div class="input-group">
			<span class="input-group-text">₺</span>
			<input type="text" class="form-control" asp-for="Salary"></input>

		</div>
		<span asp-validation-for="Salary" class="text-danger"></span>
	</div>
	<div class="d-grid">
		<button type="submit" class="btn btn-success">Update</button>
	</div>
</form>
@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

CalisanBilgiler/CalisanBilgiler/Views/Calisan/Index.cshtml
@model List<CalisanBilgiler.Models.CalisanViewModel>
@{
	ViewData["Title"] = "Calisan Bilgileri";
	var successMessage = TempData["successMessage"]?.ToString();
	var errorMessage = TempData["errorMessage"]?.ToString();
}
<h3>Calisan Bilgileri</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(@successMessage))
{
	<div class="alert alert-success">
		<strong>Basarili!</strong>@successMessage
		<button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>
	</div>
	
}
else if (!string.IsNullOrWhiteSpace(@errorMessage))
{
	<div class="alert alert-danger">
		<strong>Error!</strong>@errorMessage
		<button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>
	</div>
	
}
<form>
	<button asp-action="Create" asp-controller="Calisan"class="btn btn-primary nb-3">Calisan Oluştur</button>
	<table class="table table-responsive table-hover table-bordered">
		<thead>
			<tr>
				<tr class="table-active">
				<th class="text-center">Id</th>
				<th class="text-center">Name</th>
				<th class="text-center">Date Of Birth</th>
				<th class="text-center">E-Mail</th>
				<th class="text-center">Salary</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			@if (Model != null && Model.Any())
			{
				@foreach(var calisan in Model)
				{
					<tr>
						<td class="text-center">@calisan.Id</td>
						<td>@calisan.FullName</td>
						<td class="text-center">@calisan.DateOfBirth.ToString("dd/MM/yyyy")</td>
						<td>@calisan.Email</td>
						<td class="text-end">@calisan.Salary</td>
						<td>
							<div class="btn group btn-group-sm">
								<a asp-controller="calisan"asp-action="Edit" asp-route-id="@calisan.Id"
								class="btn btn-primary">Edit</a>
								<a asp-controller="calisan" asp-action="Delete" asp-route-id="@calisan.Id"
								class="btn btn-danger">Delete</a>

							</div>
						</td>
					</tr>
				}
				
			}
			else
			{
				<tr>
					<td colspan="6">
						<div>
							No Employees Available at this moment!
						</div>

					</td>
				</tr>
			}
		</tbody>
	</table>


</form>

CalisanBilgiler/CalisanBilgiler/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sirketimize Hosgeldiniz!</h1>
    <p>KRC KARGO LTD.ŞTİ <a href=""></a>.</p>
    <p>Calışan bilgilerine erişmek için sol üstteki menüden CalisanBilgi ekranına tıklayınız <a href=""></a>.</p>
</div>

CalisanBilgiler/CalisanBilgiler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalisanBilgiler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CalisanBilgiler.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalisanBilgiler</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                          
                        </li>
                        <li class="nav-item">
                           
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calisan" asp-action="Index">Calisan Bilgi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalisanBilgiler - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
	<script src="~/js/customjs.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>